### ISSUE TITLE
Duplicate keys in site.json

### ISSUE THREAD

**Issue by mundry** [rebelchris/astro-portfolio#2]
Hi,

there are two duplicate keys for 2020 and 2012 in the `journey` object of site.json.
https://github.com/rebelchris/astro-portfolio/blob/ded37cc9f148c3cf6e9216335e370c7357e32566/src/data/site.json#L79-L91

Possibly this one is meant to be 1992.
https://github.com/rebelchris/astro-portfolio/blob/ded37cc9f148c3cf6e9216335e370c7357e32566/src/data/site.json#L137-L139

In each case the first occurrence of the key gets overwritten by the second occurrence, which results in only the values of the second occurrence being displayed on the site.

**Comment by rebelchris** [comment]
Thanks for noting this, must have been a copy-paste error from the old data.
Will amend it ✨
